# -*- coding: utf-8 -*-
# Autor: Luis Quiroz Burga

from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.main_ui import *
from models.ui.graph_2d_view import *
from spectral import *

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1200, 801)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 131))
		self.groupBox.setObjectName("groupBox")
		self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 101))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.button_open_sample = QtWidgets.QPushButton(self.gridLayoutWidget)
		font = QtGui.QFont()
		font.setBold(True)
		font.setItalic(False)
		font.setWeight(75)
		font.setStrikeOut(False)
		self.button_open_sample.setFont(font)
		self.button_open_sample.setObjectName("button_open_sample")
		self.gridLayout.addWidget(self.button_open_sample, 0, 0, 1, 1)
		self.button_new_sample = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.button_new_sample.setObjectName("button_new_sample")
		self.gridLayout.addWidget(self.button_new_sample, 1, 0, 1, 1)
		self.button_fast_test = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.button_fast_test.setObjectName("button_fast_test")
		self.gridLayout.addWidget(self.button_fast_test, 2, 0, 1, 1)
		self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
		self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 20, 131, 101))
		self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
		self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
		self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.button_print = QtWidgets.QPushButton(self.gridLayoutWidget_2)
		self.button_print.setObjectName("button_print")
		self.gridLayout_3.addWidget(self.button_print, 1, 0, 1, 1)
		self.button_save_sample = QtWidgets.QPushButton(self.gridLayoutWidget_2)
		self.button_save_sample.setObjectName("button_save_sample")
		self.gridLayout_3.addWidget(self.button_save_sample, 0, 0, 1, 1)
		self.button_configuration = QtWidgets.QPushButton(self.gridLayoutWidget_2)
		self.button_configuration.setObjectName("button_configuration")
		self.gridLayout_3.addWidget(self.button_configuration, 2, 0, 1, 1)
		self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox_2.setGeometry(QtCore.QRect(10, 340, 291, 211))
		self.groupBox_2.setObjectName("groupBox_2")
		self.text_browser_info = QtWidgets.QTextBrowser(self.groupBox_2)
		self.text_browser_info.setGeometry(QtCore.QRect(10, 20, 271, 181))
		self.text_browser_info.setObjectName("text_browser_info")
		self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox_3.setGeometry(QtCore.QRect(10, 560, 291, 201))
		self.groupBox_3.setObjectName("groupBox_3")
		self.list_view_logs = QtWidgets.QListWidget(self.groupBox_3)
		self.list_view_logs.setGeometry(QtCore.QRect(10, 20, 271, 171))
		self.list_view_logs.setObjectName("list_view_logs")
		self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox_4.setGeometry(QtCore.QRect(10, 150, 291, 181))
		self.groupBox_4.setObjectName("groupBox_4")
		self.tree_information = QtWidgets.QTreeWidget(self.groupBox_4)
		self.tree_information.setGeometry(QtCore.QRect(10, 20, 271, 151))
		self.tree_information.setObjectName("tree_information")
		self.tree_information.headerItem().setText(0, "1")
		self.tabWidget_2 = QtWidgets.QTabWidget(self.centralwidget)
		self.tabWidget_2.setGeometry(QtCore.QRect(310, 620, 591, 141))
		self.tabWidget_2.setObjectName("tabWidget_2")
		self.tab_3 = QtWidgets.QWidget()
		self.tab_3.setObjectName("tab_3")
		self.graph_view_spectre = QtWidgets.QGraphicsView(self.tab_3)
		self.graph_view_spectre.setGeometry(QtCore.QRect(0, 0, 591, 121))
		self.graph_view_spectre.setObjectName("graph_view_spectre")
		self.tabWidget_2.addTab(self.tab_3, "")
		self.tab_4 = QtWidgets.QWidget()
		self.tab_4.setObjectName("tab_4")
		self.graph_view_plot = QtWidgets.QGraphicsView(self.tab_4)
		self.graph_view_plot.setGeometry(QtCore.QRect(0, 0, 591, 121))
		self.graph_view_plot.setObjectName("graph_view_plot")
		self.tabWidget_2.addTab(self.tab_4, "")
		self.tabWidget_3 = QtWidgets.QTabWidget(self.centralwidget)
		self.tabWidget_3.setGeometry(QtCore.QRect(910, 0, 281, 731))
		self.tabWidget_3.setObjectName("tabWidget_3")
		self.tab_6 = QtWidgets.QWidget()
		self.tab_6.setObjectName("tab_6")
		self.label = QtWidgets.QLabel(self.tab_6)
		self.label.setGeometry(QtCore.QRect(20, 10, 41, 16))
		font = QtGui.QFont()
		font.setPointSize(11)
		self.label.setFont(font)
		self.label.setObjectName("label")
		self.combo_mode = QtWidgets.QComboBox(self.tab_6)
		self.combo_mode.setGeometry(QtCore.QRect(70, 10, 191, 21))
		self.combo_mode.setObjectName("combo_mode")
		self.slider_red_band = QtWidgets.QSlider(self.tab_6)
		self.slider_red_band.setGeometry(QtCore.QRect(10, 120, 251, 22))
		self.slider_red_band.setOrientation(QtCore.Qt.Horizontal)
		self.slider_red_band.setObjectName("slider_red_band")
		self.label_2 = QtWidgets.QLabel(self.tab_6)
		self.label_2.setGeometry(QtCore.QRect(130, 90, 31, 16))
		self.label_2.setObjectName("label_2")
		self.label_3 = QtWidgets.QLabel(self.tab_6)
		self.label_3.setGeometry(QtCore.QRect(130, 150, 31, 16))
		self.label_3.setObjectName("label_3")
		self.slider_green_band = QtWidgets.QSlider(self.tab_6)
		self.slider_green_band.setGeometry(QtCore.QRect(10, 180, 251, 22))
		self.slider_green_band.setOrientation(QtCore.Qt.Horizontal)
		self.slider_green_band.setObjectName("slider_green_band")
		self.slider_blue_band = QtWidgets.QSlider(self.tab_6)
		self.slider_blue_band.setGeometry(QtCore.QRect(10, 240, 251, 22))
		self.slider_blue_band.setOrientation(QtCore.Qt.Horizontal)
		self.slider_blue_band.setObjectName("slider_blue_band")
		self.label_4 = QtWidgets.QLabel(self.tab_6)
		self.label_4.setGeometry(QtCore.QRect(130, 210, 31, 16))
		self.label_4.setObjectName("label_4")
		self.red_text_box = QtWidgets.QLineEdit(self.tab_6)
		self.red_text_box.setGeometry(QtCore.QRect(240, 90, 31, 20))
		self.red_text_box.setObjectName("red_text_box")
		self.green_text_box = QtWidgets.QLineEdit(self.tab_6)
		self.green_text_box.setGeometry(QtCore.QRect(240, 150, 31, 20))
		self.green_text_box.setObjectName("green_text_box")
		self.blue_text_box = QtWidgets.QLineEdit(self.tab_6)
		self.blue_text_box.setGeometry(QtCore.QRect(240, 210, 31, 20))
		self.blue_text_box.setObjectName("blue_text_box")
		self.mode_title = QtWidgets.QLabel(self.tab_6)
		self.mode_title.setGeometry(QtCore.QRect(10, 50, 161, 31))
		font = QtGui.QFont()
		font.setPointSize(11)
		font.setBold(True)
		font.setWeight(75)
		self.mode_title.setFont(font)
		self.mode_title.setObjectName("mode_title")
		self.nbands = QtWidgets.QLabel(self.tab_6)
		self.nbands.setGeometry(QtCore.QRect(170, 50, 101, 31))
		font = QtGui.QFont()
		font.setPointSize(9)
		font.setBold(True)
		font.setWeight(75)
		self.nbands.setFont(font)
		self.nbands.setAlignment(QtCore.Qt.AlignCenter)
		self.nbands.setObjectName("nbands")
		self.tabWidget_3.addTab(self.tab_6, "")
		self.tab_5 = QtWidgets.QWidget()
		self.tab_5.setObjectName("tab_5")
		self.button_3d_hypercube = QtWidgets.QPushButton(self.tab_5)
		self.button_3d_hypercube.setGeometry(QtCore.QRect(10, 10, 251, 31))
		self.button_3d_hypercube.setObjectName("button_3d_hypercube")
		self.button_pixel_analityc = QtWidgets.QPushButton(self.tab_5)
		self.button_pixel_analityc.setGeometry(QtCore.QRect(10, 50, 251, 31))
		self.button_pixel_analityc.setObjectName("button_pixel_analityc")
		self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
		self.groupBox_6.setGeometry(QtCore.QRect(10, 90, 251, 141))
		self.groupBox_6.setObjectName("groupBox_6")
		self.lasso_button = QtWidgets.QPushButton(self.groupBox_6)
		self.lasso_button.setGeometry(QtCore.QRect(10, 20, 111, 23))
		self.lasso_button.setObjectName("lasso_button")
		self.rectangle_button = QtWidgets.QPushButton(self.groupBox_6)
		self.rectangle_button.setGeometry(QtCore.QRect(130, 20, 111, 23))
		self.rectangle_button.setObjectName("rectangle_button")
		self.tabWidget_3.addTab(self.tab_5, "")
		self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox_5.setGeometry(QtCore.QRect(309, 0, 601, 621))
		self.groupBox_5.setObjectName("groupBox_5")
		self.graph_2d_view = graph_2d_view(self.groupBox_5)
		self.graph_2d_view.setGeometry(QtCore.QRect(0, 9, 600, 600))
		self.graph_2d_view.setObjectName("graph_2d_view")
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
		self.menubar.setObjectName("menubar")
		self.menuArchivo = QtWidgets.QMenu(self.menubar)
		self.menuArchivo.setObjectName("menuArchivo")
		self.menuEdici_n = QtWidgets.QMenu(self.menubar)
		self.menuEdici_n.setObjectName("menuEdici_n")
		self.menuAyuda = QtWidgets.QMenu(self.menubar)
		self.menuAyuda.setObjectName("menuAyuda")
		MainWindow.setMenuBar(self.menubar)
		self.menubar.addAction(self.menuArchivo.menuAction())
		self.menubar.addAction(self.menuEdici_n.menuAction())
		self.menubar.addAction(self.menuAyuda.menuAction())

		self.retranslateUi(MainWindow)
		self.tabWidget_2.setCurrentIndex(0)
		self.tabWidget_3.setCurrentIndex(0)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

		setupUi_definitions(self)

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
		self.groupBox.setTitle(_translate("MainWindow", "Opciones"))
		self.button_open_sample.setText(_translate("MainWindow", "Abrir Muestra"))
		self.button_new_sample.setText(_translate("MainWindow", "Nueva Muestra"))
		self.button_fast_test.setText(_translate("MainWindow", "Fast Test"))
		self.button_print.setText(_translate("MainWindow", "Imprimir"))
		self.button_save_sample.setText(_translate("MainWindow", "Guardar Muestra"))
		self.button_configuration.setText(_translate("MainWindow", "Configuración"))
		self.groupBox_2.setTitle(_translate("MainWindow", "Información de la Muestra"))
		self.groupBox_3.setTitle(_translate("MainWindow", "Logs"))
		self.groupBox_4.setTitle(_translate("MainWindow", "Árbol de Información"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Espectro"))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Data Plot"))
		self.label.setText(_translate("MainWindow", "Modo"))
		self.label_2.setText(_translate("MainWindow", "Rojo"))
		self.label_3.setText(_translate("MainWindow", "Verde"))
		self.label_4.setText(_translate("MainWindow", "Azul"))
		self.mode_title.setText(_translate("MainWindow", "Número de Bandas:"))
		self.nbands.setText(_translate("MainWindow", "0"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("MainWindow", "Propiedades"))
		self.button_3d_hypercube.setText(_translate("MainWindow", "Visualizar Hipercubo en 3D"))
		self.button_pixel_analityc.setText(_translate("MainWindow", "Análisis de Píxeles"))
		self.groupBox_6.setTitle(_translate("MainWindow", "Herramientas de Selección de Datos"))
		self.lasso_button.setText(_translate("MainWindow", "Lasso Selector"))
		self.rectangle_button.setText(_translate("MainWindow", "Rectangle Selector"))
		self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_5), _translate("MainWindow", "Herramientas"))
		self.groupBox_5.setTitle(_translate("MainWindow", "Muestra 2D"))
		self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
		self.menuEdici_n.setTitle(_translate("MainWindow", "Edición"))
		self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))

	def _load_test(self):
		load_test(self)

	def _render_sample(self):
		render_sample(self)     

	def _pixel_analytic(self):
		pixel_analytic(self)

	def _render_hypercube(self):
		render_hypercube(self)

	def _slider_rgb(self):
		slider_rgb(self)

	def _change_rgb_values(self):
		change_rgb_values(self)

	def _lasso_selector_actived(self):
		lasso_selector_actived(self)

	def _combo_mode_activaded(self, text):
		combo_mode_activaded(self, text)


if __name__ == "__main__":
	main_ui(Ui_MainWindow())

