# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_2.0.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1128, 794)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_open_sample = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.button_open_sample.setFont(font)
        self.button_open_sample.setObjectName("button_open_sample")
        self.horizontalLayout_2.addWidget(self.button_open_sample)
        self.button_fast_test = QtWidgets.QPushButton(self.centralwidget)
        self.button_fast_test.setObjectName("button_fast_test")
        self.horizontalLayout_2.addWidget(self.button_fast_test)
        self.lasso_button = QtWidgets.QPushButton(self.centralwidget)
        self.lasso_button.setObjectName("lasso_button")
        self.horizontalLayout_2.addWidget(self.lasso_button)
        self.button_pixel_analityc = QtWidgets.QPushButton(self.centralwidget)
        self.button_pixel_analityc.setObjectName("button_pixel_analityc")
        self.horizontalLayout_2.addWidget(self.button_pixel_analityc)
        self.button_3d_hypercube = QtWidgets.QPushButton(self.centralwidget)
        self.button_3d_hypercube.setObjectName("button_3d_hypercube")
        self.horizontalLayout_2.addWidget(self.button_3d_hypercube)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem)
        self.text_browser_info = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_browser_info.setMinimumSize(QtCore.QSize(0, 150))
        self.text_browser_info.setMaximumSize(QtCore.QSize(300, 200))
        self.text_browser_info.setObjectName("text_browser_info")
        self.horizontalLayout_12.addWidget(self.text_browser_info)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.graph_plot_view = graph_plot_view(self.centralwidget)
        self.graph_plot_view.setMinimumSize(QtCore.QSize(600, 500))
        self.graph_plot_view.setMaximumSize(QtCore.QSize(700, 400))
        self.graph_plot_view.setObjectName("graph_plot_view")
        self.verticalLayout_9.addWidget(self.graph_plot_view)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 0, 2, 4, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.add_roi_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_roi_button.setObjectName("add_roi_button")
        self.horizontalLayout_8.addWidget(self.add_roi_button)
        self.export_roi_button = QtWidgets.QPushButton(self.centralwidget)
        self.export_roi_button.setObjectName("export_roi_button")
        self.horizontalLayout_8.addWidget(self.export_roi_button)
        self.graph_profile_button = QtWidgets.QPushButton(self.centralwidget)
        self.graph_profile_button.setObjectName("graph_profile_button")
        self.horizontalLayout_8.addWidget(self.graph_profile_button)
        self.graph_standar_des_button = QtWidgets.QPushButton(self.centralwidget)
        self.graph_standar_des_button.setObjectName("graph_standar_des_button")
        self.horizontalLayout_8.addWidget(self.graph_standar_des_button)
        self.gridLayout_4.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)
        self.graph_2d_view = graph_2d_view(self.centralwidget)
        self.graph_2d_view.setMinimumSize(QtCore.QSize(500, 500))
        self.graph_2d_view.setMaximumSize(QtCore.QSize(1200, 1200))
        self.graph_2d_view.setObjectName("graph_2d_view")
        self.gridLayout_4.addWidget(self.graph_2d_view, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.slider_red_band = QtWidgets.QSlider(self.centralwidget)
        self.slider_red_band.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_red_band.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slider_red_band.setOrientation(QtCore.Qt.Horizontal)
        self.slider_red_band.setObjectName("slider_red_band")
        self.horizontalLayout_3.addWidget(self.slider_red_band)
        self.red_text_box = QtWidgets.QLineEdit(self.centralwidget)
        self.red_text_box.setMaximumSize(QtCore.QSize(30, 20))
        self.red_text_box.setObjectName("red_text_box")
        self.horizontalLayout_3.addWidget(self.red_text_box)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.slider_blue_band = QtWidgets.QSlider(self.centralwidget)
        self.slider_blue_band.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_blue_band.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slider_blue_band.setOrientation(QtCore.Qt.Horizontal)
        self.slider_blue_band.setObjectName("slider_blue_band")
        self.horizontalLayout_4.addWidget(self.slider_blue_band)
        self.blue_text_box = QtWidgets.QLineEdit(self.centralwidget)
        self.blue_text_box.setMaximumSize(QtCore.QSize(30, 20))
        self.blue_text_box.setObjectName("blue_text_box")
        self.horizontalLayout_4.addWidget(self.blue_text_box)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.slider_green_band = QtWidgets.QSlider(self.centralwidget)
        self.slider_green_band.setMinimumSize(QtCore.QSize(150, 0))
        self.slider_green_band.setMaximumSize(QtCore.QSize(200, 16777215))
        self.slider_green_band.setOrientation(QtCore.Qt.Horizontal)
        self.slider_green_band.setObjectName("slider_green_band")
        self.horizontalLayout_5.addWidget(self.slider_green_band)
        self.green_text_box = QtWidgets.QLineEdit(self.centralwidget)
        self.green_text_box.setMaximumSize(QtCore.QSize(30, 20))
        self.green_text_box.setObjectName("green_text_box")
        self.horizontalLayout_5.addWidget(self.green_text_box)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.combo_mode = QtWidgets.QComboBox(self.centralwidget)
        self.combo_mode.setMinimumSize(QtCore.QSize(200, 0))
        self.combo_mode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.combo_mode.setObjectName("combo_mode")
        self.verticalLayout_10.addWidget(self.combo_mode)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.mode_title = QtWidgets.QLabel(self.centralwidget)
        self.mode_title.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.mode_title.setFont(font)
        self.mode_title.setAlignment(QtCore.Qt.AlignCenter)
        self.mode_title.setObjectName("mode_title")
        self.verticalLayout_10.addWidget(self.mode_title)
        self.nbands = QtWidgets.QLabel(self.centralwidget)
        self.nbands.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.nbands.setFont(font)
        self.nbands.setAlignment(QtCore.Qt.AlignCenter)
        self.nbands.setObjectName("nbands")
        self.verticalLayout_10.addWidget(self.nbands)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem13)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        self.gridLayout_4.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1128, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEdici_n = QtWidgets.QMenu(self.menubar)
        self.menuEdici_n.setObjectName("menuEdici_n")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEdici_n.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_open_sample.setText(_translate("MainWindow", "Abrir Muestra"))
        self.button_fast_test.setText(_translate("MainWindow", "Test"))
        self.lasso_button.setText(_translate("MainWindow", "Seleccionar ROI"))
        self.button_pixel_analityc.setText(_translate("MainWindow", "Análisis 2D"))
        self.button_3d_hypercube.setText(_translate("MainWindow", "3D Hypercube"))
        self.label_5.setText(_translate("MainWindow", "Información de la Imagen"))
        self.label_6.setText(_translate("MainWindow", "Gráficas"))
        self.add_roi_button.setText(_translate("MainWindow", "Guardar ROI"))
        self.export_roi_button.setText(_translate("MainWindow", "Exportar ROI"))
        self.graph_profile_button.setText(_translate("MainWindow", "Graficar Mediana ROI"))
        self.graph_standar_des_button.setText(_translate("MainWindow", "Graficar Desviación Estándar ROI"))
        self.label_2.setText(_translate("MainWindow", "Rojo"))
        self.label_4.setText(_translate("MainWindow", "Azul"))
        self.label_3.setText(_translate("MainWindow", "Verde"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "Modo:"))
        self.mode_title.setText(_translate("MainWindow", "Número de Bandas:"))
        self.nbands.setText(_translate("MainWindow", "0"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuEdici_n.setTitle(_translate("MainWindow", "Edición"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))

from graph_2d_view import graph_2d_view
from graph_plot_view import graph_plot_view

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

